version: '3.8'
services:
  db:
    container_name: flask_mysql
    restart: always
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'admin' # TODO: Change this
      MYSQL_USER: 'drduongspa'
      MYSQL_PASS: 'password'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/sql/drduongspa.sql
volumes:
  db:
    driver: local