version: '2'
services:
  mysql:
    container_name: flask_mysql
    restart: always
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'admin' # TODO: Change this
      MYSQL_USER: 'drduongspa'
      MYSQL_PASS: 'password'
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume: