version: '3.8'
services:
  db:
    container_name: mydb
    restart: always
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: majesticnails
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'majestic123'
      MYSQL_PASS: 'Majestic&1354a'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/test.sql
volumes:
  db:
    driver: local